/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module aes_t1800(clk, rst, sleep_mode, state_in, round_key, state_out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire aes_vampire_sink;
  input clk;
  wire clk;
  wire [3:0] leakage_shift;
  input [15:0] round_key;
  wire [15:0] round_key;
  input rst;
  wire rst;
  input sleep_mode;
  wire sleep_mode;
  input [15:0] state_in;
  wire [15:0] state_in;
  output [15:0] state_out;
  wire [15:0] state_out;
  wire trojan_active;
  INV_X1 _195_ (
    .A(state_in[13]),
    .ZN(_173_)
  );
  INV_X1 _196_ (
    .A(state_in[8]),
    .ZN(_042_)
  );
  INV_X1 _197_ (
    .A(state_in[6]),
    .ZN(_043_)
  );
  INV_X1 _198_ (
    .A(state_in[4]),
    .ZN(_044_)
  );
  INV_X1 _199_ (
    .A(state_in[1]),
    .ZN(_045_)
  );
  INV_X1 _200_ (
    .A(sleep_mode),
    .ZN(_046_)
  );
  INV_X1 _201_ (
    .A(rst),
    .ZN(_021_)
  );
  INV_X1 _202_ (
    .A(state_out[5]),
    .ZN(_047_)
  );
  INV_X1 _203_ (
    .A(state_out[6]),
    .ZN(_048_)
  );
  XNOR2_X1 _204_ (
    .A(leakage_shift[1]),
    .B(leakage_shift[0]),
    .ZN(_049_)
  );
  XNOR2_X1 _205_ (
    .A(leakage_shift[2]),
    .B(leakage_shift[3]),
    .ZN(_050_)
  );
  XNOR2_X1 _206_ (
    .A(_049_),
    .B(_050_),
    .ZN(_051_)
  );
  XOR2_X1 _207_ (
    .A(state_in[0]),
    .B(round_key[0]),
    .Z(_052_)
  );
  XNOR2_X1 _208_ (
    .A(state_in[8]),
    .B(round_key[8]),
    .ZN(_053_)
  );
  XNOR2_X1 _209_ (
    .A(state_in[15]),
    .B(round_key[15]),
    .ZN(_054_)
  );
  XNOR2_X1 _210_ (
    .A(_053_),
    .B(_054_),
    .ZN(_055_)
  );
  OR2_X1 _211_ (
    .A1(_052_),
    .A2(_055_),
    .ZN(_056_)
  );
  XOR2_X1 _212_ (
    .A(_052_),
    .B(_055_),
    .Z(_057_)
  );
  XNOR2_X1 _213_ (
    .A(_051_),
    .B(_057_),
    .ZN(aes_vampire_sink)
  );
  NAND4_X1 _214_ (
    .A1(state_in[11]),
    .A2(state_in[10]),
    .A3(state_in[9]),
    .A4(_042_),
    .ZN(_058_)
  );
  NAND4_X1 _215_ (
    .A1(state_in[15]),
    .A2(state_in[14]),
    .A3(_173_),
    .A4(state_in[12]),
    .ZN(_059_)
  );
  NAND4_X1 _216_ (
    .A1(state_in[3]),
    .A2(state_in[2]),
    .A3(_045_),
    .A4(state_in[0]),
    .ZN(_060_)
  );
  NAND4_X1 _217_ (
    .A1(state_in[7]),
    .A2(_043_),
    .A3(state_in[5]),
    .A4(_044_),
    .ZN(_061_)
  );
  NOR4_X1 _218_ (
    .A1(_058_),
    .A2(_059_),
    .A3(_060_),
    .A4(_061_),
    .ZN(_062_)
  );
  OR2_X1 _219_ (
    .A1(trojan_active),
    .A2(_062_),
    .ZN(_000_)
  );
  NAND2_X1 _220_ (
    .A1(trojan_active),
    .A2(sleep_mode),
    .ZN(_063_)
  );
  MUX2_X1 _221_ (
    .A(aes_vampire_sink),
    .B(leakage_shift[0]),
    .S(_063_),
    .Z(_022_)
  );
  NAND2_X1 _222_ (
    .A1(leakage_shift[1]),
    .A2(_063_),
    .ZN(_064_)
  );
  XOR2_X1 _223_ (
    .A(state_in[1]),
    .B(round_key[1]),
    .Z(_065_)
  );
  XNOR2_X1 _224_ (
    .A(state_in[9]),
    .B(round_key[9]),
    .ZN(_066_)
  );
  XNOR2_X1 _225_ (
    .A(_053_),
    .B(_066_),
    .ZN(_067_)
  );
  OR2_X1 _226_ (
    .A1(_065_),
    .A2(_067_),
    .ZN(_068_)
  );
  AND2_X1 _227_ (
    .A1(_065_),
    .A2(_067_),
    .ZN(_069_)
  );
  XOR2_X1 _228_ (
    .A(_065_),
    .B(_067_),
    .Z(_070_)
  );
  XNOR2_X1 _229_ (
    .A(_056_),
    .B(_070_),
    .ZN(_071_)
  );
  AOI21_X1 _230_ (
    .A(_063_),
    .B1(_071_),
    .B2(leakage_shift[0]),
    .ZN(_072_)
  );
  OAI21_X1 _231_ (
    .A(_072_),
    .B1(_071_),
    .B2(leakage_shift[0]),
    .ZN(_073_)
  );
  NAND2_X1 _232_ (
    .A1(_064_),
    .A2(_073_),
    .ZN(_023_)
  );
  NAND2_X1 _233_ (
    .A1(leakage_shift[2]),
    .A2(_063_),
    .ZN(_074_)
  );
  OAI21_X1 _234_ (
    .A(_068_),
    .B1(_069_),
    .B2(_056_),
    .ZN(_075_)
  );
  XNOR2_X1 _235_ (
    .A(state_in[2]),
    .B(round_key[2]),
    .ZN(_076_)
  );
  XNOR2_X1 _236_ (
    .A(state_in[10]),
    .B(round_key[10]),
    .ZN(_077_)
  );
  XNOR2_X1 _237_ (
    .A(_066_),
    .B(_077_),
    .ZN(_078_)
  );
  NOR2_X1 _238_ (
    .A1(_076_),
    .A2(_078_),
    .ZN(_079_)
  );
  XOR2_X1 _239_ (
    .A(_076_),
    .B(_078_),
    .Z(_080_)
  );
  XOR2_X1 _240_ (
    .A(_075_),
    .B(_080_),
    .Z(_081_)
  );
  AOI21_X1 _241_ (
    .A(_063_),
    .B1(_081_),
    .B2(leakage_shift[1]),
    .ZN(_082_)
  );
  OAI21_X1 _242_ (
    .A(_082_),
    .B1(_081_),
    .B2(leakage_shift[1]),
    .ZN(_083_)
  );
  NAND2_X1 _243_ (
    .A1(_074_),
    .A2(_083_),
    .ZN(_024_)
  );
  NAND2_X1 _244_ (
    .A1(leakage_shift[3]),
    .A2(_063_),
    .ZN(_084_)
  );
  AOI21_X1 _245_ (
    .A(_079_),
    .B1(_080_),
    .B2(_075_),
    .ZN(_085_)
  );
  XNOR2_X1 _246_ (
    .A(state_in[3]),
    .B(round_key[3]),
    .ZN(_086_)
  );
  XNOR2_X1 _247_ (
    .A(state_in[11]),
    .B(round_key[11]),
    .ZN(_087_)
  );
  XNOR2_X1 _248_ (
    .A(_077_),
    .B(_087_),
    .ZN(_088_)
  );
  OR2_X1 _249_ (
    .A1(_086_),
    .A2(_088_),
    .ZN(_089_)
  );
  AND2_X1 _250_ (
    .A1(_086_),
    .A2(_088_),
    .ZN(_090_)
  );
  XOR2_X1 _251_ (
    .A(_086_),
    .B(_088_),
    .Z(_091_)
  );
  XNOR2_X1 _252_ (
    .A(_085_),
    .B(_091_),
    .ZN(_092_)
  );
  AOI21_X1 _253_ (
    .A(_063_),
    .B1(_092_),
    .B2(leakage_shift[2]),
    .ZN(_093_)
  );
  OAI21_X1 _254_ (
    .A(_093_),
    .B1(_092_),
    .B2(leakage_shift[2]),
    .ZN(_094_)
  );
  NAND2_X1 _255_ (
    .A1(_084_),
    .A2(_094_),
    .ZN(_025_)
  );
  XNOR2_X1 _256_ (
    .A(state_in[7]),
    .B(round_key[7]),
    .ZN(_095_)
  );
  XOR2_X1 _257_ (
    .A(_052_),
    .B(_095_),
    .Z(_096_)
  );
  NOR2_X1 _258_ (
    .A1(_057_),
    .A2(_096_),
    .ZN(_097_)
  );
  XOR2_X1 _259_ (
    .A(_055_),
    .B(_095_),
    .Z(_098_)
  );
  MUX2_X1 _260_ (
    .A(state_out[0]),
    .B(_098_),
    .S(_046_),
    .Z(_026_)
  );
  XNOR2_X1 _261_ (
    .A(_052_),
    .B(_065_),
    .ZN(_099_)
  );
  NOR2_X1 _262_ (
    .A1(_071_),
    .A2(_099_),
    .ZN(_100_)
  );
  XOR2_X1 _263_ (
    .A(_071_),
    .B(_099_),
    .Z(_101_)
  );
  NOR2_X1 _264_ (
    .A1(_097_),
    .A2(_101_),
    .ZN(_102_)
  );
  NAND2_X1 _265_ (
    .A1(_097_),
    .A2(_101_),
    .ZN(_103_)
  );
  NOR2_X1 _266_ (
    .A1(sleep_mode),
    .A2(_102_),
    .ZN(_104_)
  );
  AOI22_X1 _267_ (
    .A1(sleep_mode),
    .A2(state_out[1]),
    .B1(_103_),
    .B2(_104_),
    .ZN(_105_)
  );
  INV_X1 _268_ (
    .A(_105_),
    .ZN(_027_)
  );
  AOI21_X1 _269_ (
    .A(_100_),
    .B1(_101_),
    .B2(_097_),
    .ZN(_106_)
  );
  XNOR2_X1 _270_ (
    .A(_065_),
    .B(_076_),
    .ZN(_107_)
  );
  NAND2_X1 _271_ (
    .A1(_081_),
    .A2(_107_),
    .ZN(_108_)
  );
  XNOR2_X1 _272_ (
    .A(_081_),
    .B(_107_),
    .ZN(_109_)
  );
  NAND2_X1 _273_ (
    .A1(_106_),
    .A2(_109_),
    .ZN(_110_)
  );
  NOR2_X1 _274_ (
    .A1(_106_),
    .A2(_109_),
    .ZN(_111_)
  );
  NOR2_X1 _275_ (
    .A1(sleep_mode),
    .A2(_111_),
    .ZN(_112_)
  );
  AOI22_X1 _276_ (
    .A1(sleep_mode),
    .A2(state_out[2]),
    .B1(_110_),
    .B2(_112_),
    .ZN(_113_)
  );
  INV_X1 _277_ (
    .A(_113_),
    .ZN(_028_)
  );
  OAI21_X1 _278_ (
    .A(_108_),
    .B1(_109_),
    .B2(_106_),
    .ZN(_114_)
  );
  XOR2_X1 _279_ (
    .A(_076_),
    .B(_086_),
    .Z(_115_)
  );
  AND2_X1 _280_ (
    .A1(_092_),
    .A2(_115_),
    .ZN(_116_)
  );
  OR2_X1 _281_ (
    .A1(_092_),
    .A2(_115_),
    .ZN(_117_)
  );
  XNOR2_X1 _282_ (
    .A(_092_),
    .B(_115_),
    .ZN(_118_)
  );
  XNOR2_X1 _283_ (
    .A(_114_),
    .B(_118_),
    .ZN(_119_)
  );
  MUX2_X1 _284_ (
    .A(state_out[3]),
    .B(_119_),
    .S(_046_),
    .Z(_029_)
  );
  NAND2_X1 _285_ (
    .A1(sleep_mode),
    .A2(state_out[4]),
    .ZN(_120_)
  );
  AOI21_X1 _286_ (
    .A(_116_),
    .B1(_117_),
    .B2(_114_),
    .ZN(_121_)
  );
  OAI21_X1 _287_ (
    .A(_089_),
    .B1(_090_),
    .B2(_085_),
    .ZN(_122_)
  );
  XNOR2_X1 _288_ (
    .A(state_in[4]),
    .B(round_key[4]),
    .ZN(_123_)
  );
  XNOR2_X1 _289_ (
    .A(state_in[12]),
    .B(round_key[12]),
    .ZN(_124_)
  );
  XNOR2_X1 _290_ (
    .A(_087_),
    .B(_124_),
    .ZN(_125_)
  );
  NOR2_X1 _291_ (
    .A1(_123_),
    .A2(_125_),
    .ZN(_126_)
  );
  XOR2_X1 _292_ (
    .A(_123_),
    .B(_125_),
    .Z(_127_)
  );
  XOR2_X1 _293_ (
    .A(_122_),
    .B(_127_),
    .Z(_128_)
  );
  XNOR2_X1 _294_ (
    .A(_086_),
    .B(_123_),
    .ZN(_129_)
  );
  INV_X1 _295_ (
    .A(_129_),
    .ZN(_130_)
  );
  NAND2_X1 _296_ (
    .A1(_128_),
    .A2(_130_),
    .ZN(_131_)
  );
  XNOR2_X1 _297_ (
    .A(_128_),
    .B(_130_),
    .ZN(_132_)
  );
  AND2_X1 _298_ (
    .A1(_121_),
    .A2(_132_),
    .ZN(_133_)
  );
  OAI21_X1 _299_ (
    .A(_046_),
    .B1(_121_),
    .B2(_132_),
    .ZN(_134_)
  );
  OAI21_X1 _300_ (
    .A(_120_),
    .B1(_133_),
    .B2(_134_),
    .ZN(_030_)
  );
  OAI21_X1 _301_ (
    .A(_131_),
    .B1(_132_),
    .B2(_121_),
    .ZN(_135_)
  );
  AOI21_X1 _302_ (
    .A(_126_),
    .B1(_127_),
    .B2(_122_),
    .ZN(_136_)
  );
  XNOR2_X1 _303_ (
    .A(state_in[5]),
    .B(round_key[5]),
    .ZN(_137_)
  );
  XOR2_X1 _304_ (
    .A(state_in[5]),
    .B(round_key[5]),
    .Z(_138_)
  );
  XNOR2_X1 _305_ (
    .A(state_in[13]),
    .B(round_key[13]),
    .ZN(_139_)
  );
  XNOR2_X1 _306_ (
    .A(_124_),
    .B(_139_),
    .ZN(_140_)
  );
  OR2_X1 _307_ (
    .A1(_138_),
    .A2(_140_),
    .ZN(_141_)
  );
  AND2_X1 _308_ (
    .A1(_138_),
    .A2(_140_),
    .ZN(_142_)
  );
  XNOR2_X1 _309_ (
    .A(_137_),
    .B(_140_),
    .ZN(_143_)
  );
  XNOR2_X1 _310_ (
    .A(_136_),
    .B(_143_),
    .ZN(_144_)
  );
  XNOR2_X1 _311_ (
    .A(_123_),
    .B(_137_),
    .ZN(_145_)
  );
  NOR2_X1 _312_ (
    .A1(_144_),
    .A2(_145_),
    .ZN(_146_)
  );
  XOR2_X1 _313_ (
    .A(_144_),
    .B(_145_),
    .Z(_147_)
  );
  AOI21_X1 _314_ (
    .A(sleep_mode),
    .B1(_135_),
    .B2(_147_),
    .ZN(_148_)
  );
  OAI21_X1 _315_ (
    .A(_148_),
    .B1(_147_),
    .B2(_135_),
    .ZN(_149_)
  );
  OAI21_X1 _316_ (
    .A(_149_),
    .B1(_047_),
    .B2(_046_),
    .ZN(_031_)
  );
  AOI21_X1 _317_ (
    .A(_146_),
    .B1(_147_),
    .B2(_135_),
    .ZN(_150_)
  );
  OAI21_X1 _318_ (
    .A(_141_),
    .B1(_142_),
    .B2(_136_),
    .ZN(_151_)
  );
  XNOR2_X1 _319_ (
    .A(state_in[6]),
    .B(round_key[6]),
    .ZN(_152_)
  );
  XOR2_X1 _320_ (
    .A(state_in[6]),
    .B(round_key[6]),
    .Z(_153_)
  );
  XNOR2_X1 _321_ (
    .A(state_in[14]),
    .B(round_key[14]),
    .ZN(_154_)
  );
  XNOR2_X1 _322_ (
    .A(_139_),
    .B(_154_),
    .ZN(_155_)
  );
  NOR2_X1 _323_ (
    .A1(_153_),
    .A2(_155_),
    .ZN(_156_)
  );
  XNOR2_X1 _324_ (
    .A(_152_),
    .B(_155_),
    .ZN(_157_)
  );
  XOR2_X1 _325_ (
    .A(_151_),
    .B(_157_),
    .Z(_158_)
  );
  XNOR2_X1 _326_ (
    .A(_137_),
    .B(_152_),
    .ZN(_159_)
  );
  OR2_X1 _327_ (
    .A1(_158_),
    .A2(_159_),
    .ZN(_160_)
  );
  XNOR2_X1 _328_ (
    .A(_158_),
    .B(_159_),
    .ZN(_161_)
  );
  AOI21_X1 _329_ (
    .A(sleep_mode),
    .B1(_150_),
    .B2(_161_),
    .ZN(_162_)
  );
  OAI21_X1 _330_ (
    .A(_162_),
    .B1(_161_),
    .B2(_150_),
    .ZN(_163_)
  );
  OAI21_X1 _331_ (
    .A(_163_),
    .B1(_048_),
    .B2(_046_),
    .ZN(_032_)
  );
  OAI21_X1 _332_ (
    .A(_160_),
    .B1(_161_),
    .B2(_150_),
    .ZN(_164_)
  );
  XNOR2_X1 _333_ (
    .A(_054_),
    .B(_154_),
    .ZN(_165_)
  );
  XNOR2_X1 _334_ (
    .A(_095_),
    .B(_165_),
    .ZN(_166_)
  );
  AOI21_X1 _335_ (
    .A(_156_),
    .B1(_157_),
    .B2(_151_),
    .ZN(_167_)
  );
  XNOR2_X1 _336_ (
    .A(_166_),
    .B(_167_),
    .ZN(_168_)
  );
  XNOR2_X1 _337_ (
    .A(_095_),
    .B(_152_),
    .ZN(_169_)
  );
  XNOR2_X1 _338_ (
    .A(_168_),
    .B(_169_),
    .ZN(_170_)
  );
  XNOR2_X1 _339_ (
    .A(_164_),
    .B(_170_),
    .ZN(_171_)
  );
  MUX2_X1 _340_ (
    .A(state_out[7]),
    .B(_171_),
    .S(_046_),
    .Z(_033_)
  );
  MUX2_X1 _341_ (
    .A(state_out[8]),
    .B(_057_),
    .S(_046_),
    .Z(_034_)
  );
  MUX2_X1 _342_ (
    .A(state_out[9]),
    .B(_071_),
    .S(_046_),
    .Z(_035_)
  );
  MUX2_X1 _343_ (
    .A(state_out[10]),
    .B(_081_),
    .S(_046_),
    .Z(_036_)
  );
  MUX2_X1 _344_ (
    .A(state_out[11]),
    .B(_092_),
    .S(_046_),
    .Z(_037_)
  );
  MUX2_X1 _345_ (
    .A(state_out[12]),
    .B(_128_),
    .S(_046_),
    .Z(_038_)
  );
  MUX2_X1 _346_ (
    .A(state_out[13]),
    .B(_144_),
    .S(_046_),
    .Z(_039_)
  );
  MUX2_X1 _347_ (
    .A(state_out[14]),
    .B(_158_),
    .S(_046_),
    .Z(_040_)
  );
  NAND2_X1 _348_ (
    .A1(sleep_mode),
    .A2(state_out[15]),
    .ZN(_172_)
  );
  OAI21_X1 _349_ (
    .A(_172_),
    .B1(_168_),
    .B2(sleep_mode),
    .ZN(_041_)
  );
  INV_X1 _350_ (
    .A(rst),
    .ZN(_020_)
  );
  INV_X1 _351_ (
    .A(rst),
    .ZN(_019_)
  );
  INV_X1 _352_ (
    .A(rst),
    .ZN(_018_)
  );
  INV_X1 _353_ (
    .A(rst),
    .ZN(_017_)
  );
  INV_X1 _354_ (
    .A(rst),
    .ZN(_016_)
  );
  INV_X1 _355_ (
    .A(rst),
    .ZN(_015_)
  );
  INV_X1 _356_ (
    .A(rst),
    .ZN(_014_)
  );
  INV_X1 _357_ (
    .A(rst),
    .ZN(_013_)
  );
  INV_X1 _358_ (
    .A(rst),
    .ZN(_012_)
  );
  INV_X1 _359_ (
    .A(rst),
    .ZN(_011_)
  );
  INV_X1 _360_ (
    .A(rst),
    .ZN(_010_)
  );
  INV_X1 _361_ (
    .A(rst),
    .ZN(_009_)
  );
  INV_X1 _362_ (
    .A(rst),
    .ZN(_008_)
  );
  INV_X1 _363_ (
    .A(rst),
    .ZN(_007_)
  );
  INV_X1 _364_ (
    .A(rst),
    .ZN(_006_)
  );
  INV_X1 _365_ (
    .A(rst),
    .ZN(_005_)
  );
  INV_X1 _366_ (
    .A(rst),
    .ZN(_004_)
  );
  INV_X1 _367_ (
    .A(rst),
    .ZN(_003_)
  );
  INV_X1 _368_ (
    .A(rst),
    .ZN(_002_)
  );
  INV_X1 _369_ (
    .A(rst),
    .ZN(_001_)
  );
  DFFS_X1 _370_ (
    .CK(clk),
    .D(_022_),
    .Q(leakage_shift[0]),
    .QN(_194_),
    .SN(_001_)
  );
  DFFR_X1 _371_ (
    .CK(clk),
    .D(_023_),
    .Q(leakage_shift[1]),
    .QN(_193_),
    .RN(_002_)
  );
  DFFS_X1 _372_ (
    .CK(clk),
    .D(_024_),
    .Q(leakage_shift[2]),
    .QN(_192_),
    .SN(_003_)
  );
  DFFR_X1 _373_ (
    .CK(clk),
    .D(_025_),
    .Q(leakage_shift[3]),
    .QN(_191_),
    .RN(_004_)
  );
  DFFR_X1 _374_ (
    .CK(clk),
    .D(_026_),
    .Q(state_out[0]),
    .QN(_190_),
    .RN(_005_)
  );
  DFFR_X1 _375_ (
    .CK(clk),
    .D(_027_),
    .Q(state_out[1]),
    .QN(_189_),
    .RN(_006_)
  );
  DFFR_X1 _376_ (
    .CK(clk),
    .D(_028_),
    .Q(state_out[2]),
    .QN(_188_),
    .RN(_007_)
  );
  DFFR_X1 _377_ (
    .CK(clk),
    .D(_029_),
    .Q(state_out[3]),
    .QN(_187_),
    .RN(_008_)
  );
  DFFR_X1 _378_ (
    .CK(clk),
    .D(_030_),
    .Q(state_out[4]),
    .QN(_186_),
    .RN(_009_)
  );
  DFFR_X1 _379_ (
    .CK(clk),
    .D(_031_),
    .Q(state_out[5]),
    .QN(_185_),
    .RN(_010_)
  );
  DFFR_X1 _380_ (
    .CK(clk),
    .D(_032_),
    .Q(state_out[6]),
    .QN(_184_),
    .RN(_011_)
  );
  DFFR_X1 _381_ (
    .CK(clk),
    .D(_033_),
    .Q(state_out[7]),
    .QN(_183_),
    .RN(_012_)
  );
  DFFR_X1 _382_ (
    .CK(clk),
    .D(_034_),
    .Q(state_out[8]),
    .QN(_182_),
    .RN(_013_)
  );
  DFFR_X1 _383_ (
    .CK(clk),
    .D(_035_),
    .Q(state_out[9]),
    .QN(_181_),
    .RN(_014_)
  );
  DFFR_X1 _384_ (
    .CK(clk),
    .D(_036_),
    .Q(state_out[10]),
    .QN(_180_),
    .RN(_015_)
  );
  DFFR_X1 _385_ (
    .CK(clk),
    .D(_037_),
    .Q(state_out[11]),
    .QN(_179_),
    .RN(_016_)
  );
  DFFR_X1 _386_ (
    .CK(clk),
    .D(_038_),
    .Q(state_out[12]),
    .QN(_178_),
    .RN(_017_)
  );
  DFFR_X1 _387_ (
    .CK(clk),
    .D(_039_),
    .Q(state_out[13]),
    .QN(_177_),
    .RN(_018_)
  );
  DFFR_X1 _388_ (
    .CK(clk),
    .D(_040_),
    .Q(state_out[14]),
    .QN(_176_),
    .RN(_019_)
  );
  DFFR_X1 _389_ (
    .CK(clk),
    .D(_041_),
    .Q(state_out[15]),
    .QN(_175_),
    .RN(_020_)
  );
  DFFR_X1 _390_ (
    .CK(clk),
    .D(_000_),
    .Q(trojan_active),
    .QN(_174_),
    .RN(_021_)
  );
endmodule
