/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module sensor_node(clk, rst, sleep_mode, data_in, data_out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  input clk;
  wire clk;
  input [7:0] data_in;
  wire [7:0] data_in;
  output [7:0] data_out;
  wire [7:0] data_out;
  input rst;
  wire rst;
  input sleep_mode;
  wire sleep_mode;
  INV_X1 _44_ (
    .A(sleep_mode),
    .ZN(_16_)
  );
  INV_X1 _45_ (
    .A(rst),
    .ZN(_00_)
  );
  INV_X1 _46_ (
    .A(data_in[1]),
    .ZN(_17_)
  );
  INV_X1 _47_ (
    .A(data_in[5]),
    .ZN(_18_)
  );
  INV_X1 _48_ (
    .A(data_in[3]),
    .ZN(_19_)
  );
  AOI21_X1 _49_ (
    .A(data_in[2]),
    .B1(_17_),
    .B2(data_in[0]),
    .ZN(_20_)
  );
  AOI211_X1 _50_ (
    .A(data_in[2]),
    .B(_19_),
    .C1(data_in[0]),
    .C2(_17_),
    .ZN(_21_)
  );
  NAND3_X1 _51_ (
    .A1(_18_),
    .A2(data_in[4]),
    .A3(_21_),
    .ZN(_22_)
  );
  NAND4_X1 _52_ (
    .A1(_18_),
    .A2(data_in[4]),
    .A3(data_in[6]),
    .A4(_21_),
    .ZN(_23_)
  );
  XOR2_X1 _53_ (
    .A(data_in[7]),
    .B(_23_),
    .Z(_24_)
  );
  MUX2_X1 _54_ (
    .A(data_out[7]),
    .B(_24_),
    .S(_16_),
    .Z(_15_)
  );
  XNOR2_X1 _55_ (
    .A(data_in[6]),
    .B(_22_),
    .ZN(_25_)
  );
  MUX2_X1 _56_ (
    .A(data_out[6]),
    .B(_25_),
    .S(_16_),
    .Z(_14_)
  );
  AOI21_X1 _57_ (
    .A(_18_),
    .B1(data_in[4]),
    .B2(_21_),
    .ZN(_26_)
  );
  NAND2_X1 _58_ (
    .A1(_16_),
    .A2(_22_),
    .ZN(_27_)
  );
  NAND2_X1 _59_ (
    .A1(sleep_mode),
    .A2(data_out[5]),
    .ZN(_28_)
  );
  OAI21_X1 _60_ (
    .A(_28_),
    .B1(_27_),
    .B2(_26_),
    .ZN(_13_)
  );
  XNOR2_X1 _61_ (
    .A(data_in[4]),
    .B(_21_),
    .ZN(_29_)
  );
  NOR2_X1 _62_ (
    .A1(_16_),
    .A2(data_out[4]),
    .ZN(_30_)
  );
  AOI21_X1 _63_ (
    .A(_30_),
    .B1(_29_),
    .B2(_16_),
    .ZN(_12_)
  );
  XNOR2_X1 _64_ (
    .A(_19_),
    .B(_20_),
    .ZN(_31_)
  );
  MUX2_X1 _65_ (
    .A(data_out[3]),
    .B(_31_),
    .S(_16_),
    .Z(_11_)
  );
  NAND3_X1 _66_ (
    .A1(data_in[0]),
    .A2(_17_),
    .A3(data_in[2]),
    .ZN(_32_)
  );
  NOR2_X1 _67_ (
    .A1(sleep_mode),
    .A2(_20_),
    .ZN(_33_)
  );
  AOI22_X1 _68_ (
    .A1(sleep_mode),
    .A2(data_out[2]),
    .B1(_32_),
    .B2(_33_),
    .ZN(_34_)
  );
  INV_X1 _69_ (
    .A(_34_),
    .ZN(_10_)
  );
  XOR2_X1 _70_ (
    .A(data_in[0]),
    .B(data_in[1]),
    .Z(_35_)
  );
  MUX2_X1 _71_ (
    .A(data_out[1]),
    .B(_35_),
    .S(_16_),
    .Z(_09_)
  );
  MUX2_X1 _72_ (
    .A(data_in[0]),
    .B(data_out[0]),
    .S(sleep_mode),
    .Z(_08_)
  );
  INV_X1 _73_ (
    .A(rst),
    .ZN(_01_)
  );
  INV_X1 _74_ (
    .A(rst),
    .ZN(_02_)
  );
  INV_X1 _75_ (
    .A(rst),
    .ZN(_03_)
  );
  INV_X1 _76_ (
    .A(rst),
    .ZN(_04_)
  );
  INV_X1 _77_ (
    .A(rst),
    .ZN(_05_)
  );
  INV_X1 _78_ (
    .A(rst),
    .ZN(_06_)
  );
  INV_X1 _79_ (
    .A(rst),
    .ZN(_07_)
  );
  DFFR_X1 _80_ (
    .CK(clk),
    .D(_08_),
    .Q(data_out[0]),
    .QN(_43_),
    .RN(_00_)
  );
  DFFR_X1 _81_ (
    .CK(clk),
    .D(_09_),
    .Q(data_out[1]),
    .QN(_42_),
    .RN(_01_)
  );
  DFFR_X1 _82_ (
    .CK(clk),
    .D(_10_),
    .Q(data_out[2]),
    .QN(_41_),
    .RN(_02_)
  );
  DFFR_X1 _83_ (
    .CK(clk),
    .D(_11_),
    .Q(data_out[3]),
    .QN(_40_),
    .RN(_03_)
  );
  DFFR_X1 _84_ (
    .CK(clk),
    .D(_12_),
    .Q(data_out[4]),
    .QN(_39_),
    .RN(_04_)
  );
  DFFR_X1 _85_ (
    .CK(clk),
    .D(_13_),
    .Q(data_out[5]),
    .QN(_38_),
    .RN(_05_)
  );
  DFFR_X1 _86_ (
    .CK(clk),
    .D(_14_),
    .Q(data_out[6]),
    .QN(_37_),
    .RN(_06_)
  );
  DFFR_X1 _87_ (
    .CK(clk),
    .D(_15_),
    .Q(data_out[7]),
    .QN(_36_),
    .RN(_07_)
  );
endmodule
