/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module rs232_uart(clk, rst, sleep_mode, tx_start, tx_data, tx_line, tx_busy, rx_latch);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire [3:0] _161_;
  wire [3:0] _162_;
  wire [3:0] baud_cnt;
  wire [3:0] bit_idx;
  input clk;
  wire clk;
  input rst;
  wire rst;
  output [7:0] rx_latch;
  wire [7:0] rx_latch;
  wire [9:0] shift_reg;
  input sleep_mode;
  wire sleep_mode;
  output tx_busy;
  wire tx_busy;
  input [7:0] tx_data;
  wire [7:0] tx_data;
  output tx_line;
  wire tx_line;
  input tx_start;
  wire tx_start;
  INV_X1 _163_ (
    .A(shift_reg[8]),
    .ZN(_137_)
  );
  INV_X1 _164_ (
    .A(shift_reg[0]),
    .ZN(_138_)
  );
  INV_X1 _165_ (
    .A(bit_idx[1]),
    .ZN(_057_)
  );
  INV_X1 _166_ (
    .A(bit_idx[0]),
    .ZN(_058_)
  );
  INV_X1 _167_ (
    .A(baud_cnt[2]),
    .ZN(_059_)
  );
  INV_X1 _168_ (
    .A(rx_latch[7]),
    .ZN(_060_)
  );
  INV_X1 _169_ (
    .A(rx_latch[6]),
    .ZN(_061_)
  );
  INV_X1 _170_ (
    .A(rx_latch[5]),
    .ZN(_062_)
  );
  INV_X1 _171_ (
    .A(rx_latch[4]),
    .ZN(_063_)
  );
  INV_X1 _172_ (
    .A(rx_latch[3]),
    .ZN(_064_)
  );
  INV_X1 _173_ (
    .A(rx_latch[2]),
    .ZN(_065_)
  );
  INV_X1 _174_ (
    .A(rst),
    .ZN(_005_)
  );
  INV_X1 _175_ (
    .A(tx_busy),
    .ZN(_066_)
  );
  INV_X1 _176_ (
    .A(tx_data[1]),
    .ZN(_067_)
  );
  INV_X1 _177_ (
    .A(tx_data[2]),
    .ZN(_068_)
  );
  INV_X1 _178_ (
    .A(tx_data[3]),
    .ZN(_069_)
  );
  INV_X1 _179_ (
    .A(tx_data[4]),
    .ZN(_070_)
  );
  INV_X1 _180_ (
    .A(tx_data[6]),
    .ZN(_071_)
  );
  XOR2_X1 _181_ (
    .A(tx_data[2]),
    .B(tx_data[3]),
    .Z(_072_)
  );
  XNOR2_X1 _182_ (
    .A(tx_data[0]),
    .B(tx_data[1]),
    .ZN(_073_)
  );
  XNOR2_X1 _183_ (
    .A(_072_),
    .B(_073_),
    .ZN(_074_)
  );
  XNOR2_X1 _184_ (
    .A(tx_data[4]),
    .B(tx_data[5]),
    .ZN(_075_)
  );
  XNOR2_X1 _185_ (
    .A(tx_data[6]),
    .B(tx_data[7]),
    .ZN(_076_)
  );
  XNOR2_X1 _186_ (
    .A(_075_),
    .B(_076_),
    .ZN(_077_)
  );
  XNOR2_X1 _187_ (
    .A(_074_),
    .B(_077_),
    .ZN(_078_)
  );
  NAND2_X1 _188_ (
    .A1(_004_),
    .A2(tx_start),
    .ZN(_079_)
  );
  AOI21_X1 _189_ (
    .A(sleep_mode),
    .B1(_079_),
    .B2(_066_),
    .ZN(_080_)
  );
  NOR4_X1 _190_ (
    .A1(baud_cnt[3]),
    .A2(baud_cnt[2]),
    .A3(_161_[0]),
    .A4(_003_),
    .ZN(_081_)
  );
  OAI21_X1 _191_ (
    .A(_080_),
    .B1(_081_),
    .B2(_004_),
    .ZN(_082_)
  );
  NOR4_X1 _192_ (
    .A1(bit_idx[2]),
    .A2(bit_idx[1]),
    .A3(_162_[0]),
    .A4(_002_),
    .ZN(_083_)
  );
  NAND2_X1 _193_ (
    .A1(_081_),
    .A2(_083_),
    .ZN(_084_)
  );
  NOR2_X1 _194_ (
    .A1(_004_),
    .A2(_084_),
    .ZN(_085_)
  );
  NOR2_X1 _195_ (
    .A1(_082_),
    .A2(_085_),
    .ZN(_086_)
  );
  NOR2_X1 _196_ (
    .A1(sleep_mode),
    .A2(_079_),
    .ZN(_087_)
  );
  OR2_X1 _197_ (
    .A1(sleep_mode),
    .A2(_079_),
    .ZN(_088_)
  );
  NOR2_X1 _198_ (
    .A1(_078_),
    .A2(_088_),
    .ZN(_089_)
  );
  AOI21_X1 _199_ (
    .A(_089_),
    .B1(_082_),
    .B2(_137_),
    .ZN(_056_)
  );
  MUX2_X1 _200_ (
    .A(tx_data[6]),
    .B(shift_reg[8]),
    .S(_079_),
    .Z(_090_)
  );
  MUX2_X1 _201_ (
    .A(_090_),
    .B(shift_reg[7]),
    .S(_082_),
    .Z(_055_)
  );
  MUX2_X1 _202_ (
    .A(tx_data[5]),
    .B(shift_reg[7]),
    .S(_079_),
    .Z(_091_)
  );
  MUX2_X1 _203_ (
    .A(_091_),
    .B(shift_reg[6]),
    .S(_082_),
    .Z(_054_)
  );
  MUX2_X1 _204_ (
    .A(tx_data[4]),
    .B(shift_reg[6]),
    .S(_079_),
    .Z(_092_)
  );
  MUX2_X1 _205_ (
    .A(_092_),
    .B(shift_reg[5]),
    .S(_082_),
    .Z(_053_)
  );
  MUX2_X1 _206_ (
    .A(tx_data[3]),
    .B(shift_reg[5]),
    .S(_079_),
    .Z(_093_)
  );
  MUX2_X1 _207_ (
    .A(_093_),
    .B(shift_reg[4]),
    .S(_082_),
    .Z(_052_)
  );
  MUX2_X1 _208_ (
    .A(tx_data[2]),
    .B(shift_reg[4]),
    .S(_079_),
    .Z(_094_)
  );
  MUX2_X1 _209_ (
    .A(_094_),
    .B(shift_reg[3]),
    .S(_082_),
    .Z(_051_)
  );
  MUX2_X1 _210_ (
    .A(tx_data[1]),
    .B(shift_reg[3]),
    .S(_079_),
    .Z(_095_)
  );
  MUX2_X1 _211_ (
    .A(_095_),
    .B(shift_reg[2]),
    .S(_082_),
    .Z(_050_)
  );
  MUX2_X1 _212_ (
    .A(tx_data[0]),
    .B(shift_reg[2]),
    .S(_079_),
    .Z(_096_)
  );
  MUX2_X1 _213_ (
    .A(_096_),
    .B(shift_reg[1]),
    .S(_082_),
    .Z(_049_)
  );
  AOI21_X1 _214_ (
    .A(_082_),
    .B1(_079_),
    .B2(shift_reg[1]),
    .ZN(_097_)
  );
  AOI21_X1 _215_ (
    .A(_097_),
    .B1(_082_),
    .B2(_138_),
    .ZN(_048_)
  );
  NOR3_X1 _216_ (
    .A1(_057_),
    .A2(_058_),
    .A3(_082_),
    .ZN(_098_)
  );
  NAND2_X1 _217_ (
    .A1(bit_idx[2]),
    .A2(_098_),
    .ZN(_099_)
  );
  XOR2_X1 _218_ (
    .A(bit_idx[3]),
    .B(_099_),
    .Z(_100_)
  );
  NOR2_X1 _219_ (
    .A1(_087_),
    .A2(_100_),
    .ZN(_047_)
  );
  OAI21_X1 _220_ (
    .A(_088_),
    .B1(_098_),
    .B2(bit_idx[2]),
    .ZN(_101_)
  );
  AOI21_X1 _221_ (
    .A(_101_),
    .B1(_098_),
    .B2(bit_idx[2]),
    .ZN(_046_)
  );
  AOI21_X1 _222_ (
    .A(bit_idx[1]),
    .B1(bit_idx[0]),
    .B2(_086_),
    .ZN(_102_)
  );
  NOR3_X1 _223_ (
    .A1(_087_),
    .A2(_098_),
    .A3(_102_),
    .ZN(_045_)
  );
  NAND3_X1 _224_ (
    .A1(_162_[0]),
    .A2(_079_),
    .A3(_086_),
    .ZN(_103_)
  );
  OAI21_X1 _225_ (
    .A(_103_),
    .B1(_086_),
    .B2(_058_),
    .ZN(_044_)
  );
  NAND2_X1 _226_ (
    .A1(baud_cnt[1]),
    .A2(baud_cnt[0]),
    .ZN(_104_)
  );
  AND4_X1 _227_ (
    .A1(baud_cnt[2]),
    .A2(baud_cnt[1]),
    .A3(baud_cnt[0]),
    .A4(_080_),
    .ZN(_105_)
  );
  OAI21_X1 _228_ (
    .A(_088_),
    .B1(_105_),
    .B2(baud_cnt[3]),
    .ZN(_106_)
  );
  AOI21_X1 _229_ (
    .A(_106_),
    .B1(_105_),
    .B2(baud_cnt[3]),
    .ZN(_043_)
  );
  NAND3_X1 _230_ (
    .A1(baud_cnt[1]),
    .A2(baud_cnt[0]),
    .A3(_080_),
    .ZN(_107_)
  );
  AOI21_X1 _231_ (
    .A(_081_),
    .B1(tx_start),
    .B2(_004_),
    .ZN(_108_)
  );
  OAI21_X1 _232_ (
    .A(_108_),
    .B1(_104_),
    .B2(_059_),
    .ZN(_109_)
  );
  AOI22_X1 _233_ (
    .A1(_059_),
    .A2(_107_),
    .B1(_109_),
    .B2(_080_),
    .ZN(_042_)
  );
  AOI21_X1 _234_ (
    .A(baud_cnt[1]),
    .B1(baud_cnt[0]),
    .B2(_080_),
    .ZN(_110_)
  );
  NAND2_X1 _235_ (
    .A1(_104_),
    .A2(_108_),
    .ZN(_111_)
  );
  AOI21_X1 _236_ (
    .A(_110_),
    .B1(_111_),
    .B2(_080_),
    .ZN(_041_)
  );
  NAND2_X1 _237_ (
    .A1(_161_[0]),
    .A2(_079_),
    .ZN(_112_)
  );
  NOR2_X1 _238_ (
    .A1(baud_cnt[0]),
    .A2(_080_),
    .ZN(_113_)
  );
  AOI21_X1 _239_ (
    .A(_113_),
    .B1(_112_),
    .B2(_080_),
    .ZN(_040_)
  );
  NAND2_X1 _240_ (
    .A1(tx_data[0]),
    .A2(_078_),
    .ZN(_114_)
  );
  AND4_X1 _241_ (
    .A1(tx_data[0]),
    .A2(_067_),
    .A3(tx_data[2]),
    .A4(_078_),
    .ZN(_115_)
  );
  NAND4_X1 _242_ (
    .A1(tx_data[0]),
    .A2(_067_),
    .A3(tx_data[2]),
    .A4(_078_),
    .ZN(_116_)
  );
  NAND2_X1 _243_ (
    .A1(_069_),
    .A2(_115_),
    .ZN(_117_)
  );
  NOR3_X1 _244_ (
    .A1(tx_data[3]),
    .A2(tx_data[4]),
    .A3(_116_),
    .ZN(_118_)
  );
  AND4_X1 _245_ (
    .A1(_069_),
    .A2(_070_),
    .A3(tx_data[5]),
    .A4(_115_),
    .ZN(_119_)
  );
  NAND4_X1 _246_ (
    .A1(_069_),
    .A2(_070_),
    .A3(tx_data[5]),
    .A4(_115_),
    .ZN(_120_)
  );
  OAI21_X1 _247_ (
    .A(_087_),
    .B1(_120_),
    .B2(tx_data[6]),
    .ZN(_121_)
  );
  AOI211_X1 _248_ (
    .A(tx_data[7]),
    .B(_088_),
    .C1(_119_),
    .C2(_071_),
    .ZN(_122_)
  );
  AOI21_X1 _249_ (
    .A(_122_),
    .B1(_088_),
    .B2(_060_),
    .ZN(_039_)
  );
  NOR2_X1 _250_ (
    .A1(_071_),
    .A2(_119_),
    .ZN(_123_)
  );
  OAI22_X1 _251_ (
    .A1(_061_),
    .A2(_087_),
    .B1(_121_),
    .B2(_123_),
    .ZN(_038_)
  );
  NOR2_X1 _252_ (
    .A1(tx_data[5]),
    .A2(_118_),
    .ZN(_124_)
  );
  NAND2_X1 _253_ (
    .A1(_087_),
    .A2(_120_),
    .ZN(_125_)
  );
  OAI22_X1 _254_ (
    .A1(_062_),
    .A2(_087_),
    .B1(_124_),
    .B2(_125_),
    .ZN(_037_)
  );
  AOI21_X1 _255_ (
    .A(_070_),
    .B1(_115_),
    .B2(_069_),
    .ZN(_126_)
  );
  OR2_X1 _256_ (
    .A1(_088_),
    .A2(_118_),
    .ZN(_127_)
  );
  OAI22_X1 _257_ (
    .A1(_063_),
    .A2(_087_),
    .B1(_126_),
    .B2(_127_),
    .ZN(_036_)
  );
  NAND2_X1 _258_ (
    .A1(tx_data[3]),
    .A2(_116_),
    .ZN(_128_)
  );
  NAND3_X1 _259_ (
    .A1(_087_),
    .A2(_117_),
    .A3(_128_),
    .ZN(_129_)
  );
  OAI21_X1 _260_ (
    .A(_129_),
    .B1(_087_),
    .B2(_064_),
    .ZN(_035_)
  );
  OAI21_X1 _261_ (
    .A(_068_),
    .B1(_114_),
    .B2(tx_data[1]),
    .ZN(_130_)
  );
  NAND3_X1 _262_ (
    .A1(_087_),
    .A2(_116_),
    .A3(_130_),
    .ZN(_131_)
  );
  OAI21_X1 _263_ (
    .A(_131_),
    .B1(_087_),
    .B2(_065_),
    .ZN(_034_)
  );
  XNOR2_X1 _264_ (
    .A(_067_),
    .B(_114_),
    .ZN(_132_)
  );
  MUX2_X1 _265_ (
    .A(rx_latch[1]),
    .B(_132_),
    .S(_087_),
    .Z(_033_)
  );
  XOR2_X1 _266_ (
    .A(tx_data[0]),
    .B(_078_),
    .Z(_133_)
  );
  MUX2_X1 _267_ (
    .A(rx_latch[0]),
    .B(_133_),
    .S(_087_),
    .Z(_032_)
  );
  NAND2_X1 _268_ (
    .A1(tx_busy),
    .A2(_084_),
    .ZN(_134_)
  );
  AOI21_X1 _269_ (
    .A(sleep_mode),
    .B1(_079_),
    .B2(_134_),
    .ZN(_000_)
  );
  NAND3_X1 _270_ (
    .A1(tx_busy),
    .A2(_079_),
    .A3(_081_),
    .ZN(_135_)
  );
  AOI21_X1 _271_ (
    .A(sleep_mode),
    .B1(tx_line),
    .B2(_135_),
    .ZN(_136_)
  );
  OAI21_X1 _272_ (
    .A(_136_),
    .B1(_135_),
    .B2(_138_),
    .ZN(_001_)
  );
  INV_X1 _273_ (
    .A(rst),
    .ZN(_006_)
  );
  INV_X1 _274_ (
    .A(rst),
    .ZN(_007_)
  );
  INV_X1 _275_ (
    .A(rst),
    .ZN(_008_)
  );
  INV_X1 _276_ (
    .A(rst),
    .ZN(_009_)
  );
  INV_X1 _277_ (
    .A(rst),
    .ZN(_010_)
  );
  INV_X1 _278_ (
    .A(rst),
    .ZN(_011_)
  );
  INV_X1 _279_ (
    .A(rst),
    .ZN(_012_)
  );
  INV_X1 _280_ (
    .A(rst),
    .ZN(_013_)
  );
  INV_X1 _281_ (
    .A(rst),
    .ZN(_014_)
  );
  INV_X1 _282_ (
    .A(rst),
    .ZN(_015_)
  );
  INV_X1 _283_ (
    .A(rst),
    .ZN(_016_)
  );
  INV_X1 _284_ (
    .A(rst),
    .ZN(_017_)
  );
  INV_X1 _285_ (
    .A(rst),
    .ZN(_018_)
  );
  INV_X1 _286_ (
    .A(rst),
    .ZN(_019_)
  );
  INV_X1 _287_ (
    .A(rst),
    .ZN(_020_)
  );
  INV_X1 _288_ (
    .A(rst),
    .ZN(_021_)
  );
  INV_X1 _289_ (
    .A(rst),
    .ZN(_022_)
  );
  INV_X1 _290_ (
    .A(rst),
    .ZN(_023_)
  );
  INV_X1 _291_ (
    .A(rst),
    .ZN(_024_)
  );
  INV_X1 _292_ (
    .A(rst),
    .ZN(_025_)
  );
  INV_X1 _293_ (
    .A(rst),
    .ZN(_026_)
  );
  INV_X1 _294_ (
    .A(rst),
    .ZN(_027_)
  );
  INV_X1 _295_ (
    .A(rst),
    .ZN(_028_)
  );
  INV_X1 _296_ (
    .A(rst),
    .ZN(_029_)
  );
  INV_X1 _297_ (
    .A(rst),
    .ZN(_030_)
  );
  INV_X1 _298_ (
    .A(rst),
    .ZN(_031_)
  );
  DFFR_X1 _299_ (
    .CK(clk),
    .D(_032_),
    .Q(rx_latch[0]),
    .QN(_160_),
    .RN(_005_)
  );
  DFFR_X1 _300_ (
    .CK(clk),
    .D(_033_),
    .Q(rx_latch[1]),
    .QN(_159_),
    .RN(_006_)
  );
  DFFR_X1 _301_ (
    .CK(clk),
    .D(_034_),
    .Q(rx_latch[2]),
    .QN(_158_),
    .RN(_007_)
  );
  DFFR_X1 _302_ (
    .CK(clk),
    .D(_035_),
    .Q(rx_latch[3]),
    .QN(_157_),
    .RN(_008_)
  );
  DFFR_X1 _303_ (
    .CK(clk),
    .D(_036_),
    .Q(rx_latch[4]),
    .QN(_156_),
    .RN(_009_)
  );
  DFFR_X1 _304_ (
    .CK(clk),
    .D(_037_),
    .Q(rx_latch[5]),
    .QN(_155_),
    .RN(_010_)
  );
  DFFR_X1 _305_ (
    .CK(clk),
    .D(_038_),
    .Q(rx_latch[6]),
    .QN(_154_),
    .RN(_011_)
  );
  DFFR_X1 _306_ (
    .CK(clk),
    .D(_039_),
    .Q(rx_latch[7]),
    .QN(_153_),
    .RN(_012_)
  );
  DFFS_X1 _307_ (
    .CK(clk),
    .D(_001_),
    .Q(tx_line),
    .QN(_152_),
    .SN(_013_)
  );
  DFFR_X1 _308_ (
    .CK(clk),
    .D(_000_),
    .Q(tx_busy),
    .QN(_004_),
    .RN(_014_)
  );
  DFFR_X1 _309_ (
    .CK(clk),
    .D(_040_),
    .Q(baud_cnt[0]),
    .QN(_161_[0]),
    .RN(_015_)
  );
  DFFR_X1 _310_ (
    .CK(clk),
    .D(_041_),
    .Q(baud_cnt[1]),
    .QN(_003_),
    .RN(_016_)
  );
  DFFR_X1 _311_ (
    .CK(clk),
    .D(_042_),
    .Q(baud_cnt[2]),
    .QN(_151_),
    .RN(_017_)
  );
  DFFR_X1 _312_ (
    .CK(clk),
    .D(_043_),
    .Q(baud_cnt[3]),
    .QN(_150_),
    .RN(_018_)
  );
  DFFR_X1 _313_ (
    .CK(clk),
    .D(_044_),
    .Q(bit_idx[0]),
    .QN(_162_[0]),
    .RN(_019_)
  );
  DFFR_X1 _314_ (
    .CK(clk),
    .D(_045_),
    .Q(bit_idx[1]),
    .QN(_149_),
    .RN(_020_)
  );
  DFFR_X1 _315_ (
    .CK(clk),
    .D(_046_),
    .Q(bit_idx[2]),
    .QN(_148_),
    .RN(_021_)
  );
  DFFR_X1 _316_ (
    .CK(clk),
    .D(_047_),
    .Q(bit_idx[3]),
    .QN(_002_),
    .RN(_022_)
  );
  DFFS_X1 _317_ (
    .CK(clk),
    .D(_048_),
    .Q(shift_reg[0]),
    .QN(_147_),
    .SN(_023_)
  );
  DFFS_X1 _318_ (
    .CK(clk),
    .D(_049_),
    .Q(shift_reg[1]),
    .QN(_146_),
    .SN(_024_)
  );
  DFFS_X1 _319_ (
    .CK(clk),
    .D(_050_),
    .Q(shift_reg[2]),
    .QN(_145_),
    .SN(_025_)
  );
  DFFS_X1 _320_ (
    .CK(clk),
    .D(_051_),
    .Q(shift_reg[3]),
    .QN(_144_),
    .SN(_026_)
  );
  DFFS_X1 _321_ (
    .CK(clk),
    .D(_052_),
    .Q(shift_reg[4]),
    .QN(_143_),
    .SN(_027_)
  );
  DFFS_X1 _322_ (
    .CK(clk),
    .D(_053_),
    .Q(shift_reg[5]),
    .QN(_142_),
    .SN(_028_)
  );
  DFFS_X1 _323_ (
    .CK(clk),
    .D(_054_),
    .Q(shift_reg[6]),
    .QN(_141_),
    .SN(_029_)
  );
  DFFS_X1 _324_ (
    .CK(clk),
    .D(_055_),
    .Q(shift_reg[7]),
    .QN(_140_),
    .SN(_030_)
  );
  DFFS_X1 _325_ (
    .CK(clk),
    .D(_056_),
    .Q(shift_reg[8]),
    .QN(_139_),
    .SN(_031_)
  );
  assign _161_[3:1] = baud_cnt[3:1];
  assign _162_[3:1] = bit_idx[3:1];
  assign shift_reg[9] = 1'h1;
endmodule
