/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module sensor_node(clk, rst, sleep_mode, data_in, data_out);
  wire [7:0] _000_;
  wire _001_;
  wire [3:0] _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire [7:0] _090_;
  wire [7:0] _091_;
  wire [7:0] _092_;
  wire [7:0] _093_;
  wire [7:0] _094_;
  wire [7:0] _095_;
  wire [7:0] _096_;
  wire [7:0] _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire [3:0] _115_;
  wire [3:0] _116_;
  wire [7:0] _117_;
  wire [7:0] _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire [1:0] _132_;
  wire _133_;
  wire [3:0] _134_;
  wire [1:0] _135_;
  wire _136_;
  wire [7:0] _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire [3:0] _142_;
  wire [3:0] _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire [7:0] _147_;
  wire _148_;
  wire _149_;
  wire [7:0] _150_;
  wire [7:0] _151_;
  wire [7:0] _152_;
  wire [7:0] _153_;
  wire [7:0] _154_;
  wire _155_;
  wire [7:0] _156_;
  wire _157_;
  wire [7:0] _158_;
  wire [7:0] _159_;
  wire [7:0] _160_;
  wire _161_;
  wire [7:0] _162_;
  wire [7:0] _163_;
  wire [7:0] _164_;
  wire [1023:0] _165_;
  wire [7:0] _166_;
  wire [31:0] _167_;
  wire [31:0] _168_;
  wire [7:0] _169_;
  wire [7:0] _170_;
  wire [7:0] _171_;
  wire [7:0] _172_;
  wire [7:0] _173_;
  wire [7:0] _174_;
  wire [7:0] _175_;
  wire [7:0] _176_;
  wire _177_;
  wire [7:0] _178_;
  wire _179_;
  wire [7:0] _180_;
  wire [7:0] _181_;
  wire [7:0] _182_;
  wire _183_;
  wire [7:0] _184_;
  wire [7:0] _185_;
  wire [7:0] _186_;
  wire [1023:0] _187_;
  wire [7:0] _188_;
  wire [31:0] _189_;
  wire [31:0] _190_;
  wire [7:0] _191_;
  wire [7:0] _192_;
  wire [7:0] _193_;
  wire [7:0] _194_;
  wire [7:0] _195_;
  wire [7:0] _196_;
  wire [7:0] _197_;
  wire [8:0] _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire [7:0] _219_;
  wire [7:0] _220_;
  wire [7:0] _221_;
  wire [7:0] _222_;
  wire [8:0] _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire [7:0] _244_;
  wire [7:0] _245_;
  wire [7:0] _246_;
  wire [3:0] _247_;
  wire [7:0] _248_;
  input clk;
  wire clk;
  input [7:0] data_in;
  wire [7:0] data_in;
  output [7:0] data_out;
  wire [7:0] data_out;
  input rst;
  wire rst;
  wire [7:0] shared_comb;
  input sleep_mode;
  wire sleep_mode;
  wire trojan_armed;
  wire [7:0] trojan_dup_calc;
  wire [7:0] trojan_red_cone;
  wire trojan_sink;
  wire [3:0] vampire_load;
  INV_X1 _249_ (
    .A(_024_),
    .ZN(_038_)
  );
  INV_X1 _250_ (
    .A(_021_),
    .ZN(_039_)
  );
  INV_X1 _251_ (
    .A(_022_),
    .ZN(_040_)
  );
  INV_X1 _252_ (
    .A(_020_),
    .ZN(_041_)
  );
  INV_X1 _253_ (
    .A(_083_),
    .ZN(_007_)
  );
  INV_X1 _254_ (
    .A(_085_),
    .ZN(_042_)
  );
  NAND2_X1 _255_ (
    .A1(_084_),
    .A2(_085_),
    .ZN(_043_)
  );
  AOI21_X1 _256_ (
    .A(_022_),
    .B1(_020_),
    .B2(_039_),
    .ZN(_044_)
  );
  NOR3_X1 _257_ (
    .A1(_021_),
    .A2(_040_),
    .A3(_041_),
    .ZN(_045_)
  );
  OR2_X1 _258_ (
    .A1(_044_),
    .A2(_045_),
    .ZN(_046_)
  );
  XNOR2_X1 _259_ (
    .A(_006_),
    .B(_046_),
    .ZN(_047_)
  );
  MUX2_X1 _260_ (
    .A(_047_),
    .B(_088_),
    .S(_043_),
    .Z(_071_)
  );
  XNOR2_X1 _261_ (
    .A(_021_),
    .B(_020_),
    .ZN(_048_)
  );
  XNOR2_X1 _262_ (
    .A(_005_),
    .B(_048_),
    .ZN(_049_)
  );
  MUX2_X1 _263_ (
    .A(_049_),
    .B(_087_),
    .S(_043_),
    .Z(_070_)
  );
  XOR2_X1 _264_ (
    .A(_004_),
    .B(_020_),
    .Z(_050_)
  );
  MUX2_X1 _265_ (
    .A(_050_),
    .B(_086_),
    .S(_043_),
    .Z(_069_)
  );
  OAI211_X1 _266_ (
    .A(_023_),
    .B(_040_),
    .C1(_041_),
    .C2(_021_),
    .ZN(_051_)
  );
  NOR2_X1 _267_ (
    .A1(_038_),
    .A2(_051_),
    .ZN(_052_)
  );
  NOR3_X1 _268_ (
    .A1(_038_),
    .A2(_025_),
    .A3(_051_),
    .ZN(_053_)
  );
  NAND2_X1 _269_ (
    .A1(_026_),
    .A2(_053_),
    .ZN(_054_)
  );
  XNOR2_X1 _270_ (
    .A(_026_),
    .B(_053_),
    .ZN(_055_)
  );
  NAND2_X1 _271_ (
    .A1(_034_),
    .A2(_084_),
    .ZN(_056_)
  );
  OAI21_X1 _272_ (
    .A(_056_),
    .B1(_055_),
    .B2(_084_),
    .ZN(_080_)
  );
  XOR2_X1 _273_ (
    .A(_025_),
    .B(_052_),
    .Z(_057_)
  );
  NAND2_X1 _274_ (
    .A1(_084_),
    .A2(_033_),
    .ZN(_058_)
  );
  OAI21_X1 _275_ (
    .A(_058_),
    .B1(_057_),
    .B2(_084_),
    .ZN(_079_)
  );
  XNOR2_X1 _276_ (
    .A(_038_),
    .B(_051_),
    .ZN(_059_)
  );
  NAND2_X1 _277_ (
    .A1(_084_),
    .A2(_032_),
    .ZN(_060_)
  );
  OAI21_X1 _278_ (
    .A(_060_),
    .B1(_059_),
    .B2(_084_),
    .ZN(_078_)
  );
  XNOR2_X1 _279_ (
    .A(_023_),
    .B(_044_),
    .ZN(_061_)
  );
  NAND2_X1 _280_ (
    .A1(_084_),
    .A2(_031_),
    .ZN(_062_)
  );
  OAI21_X1 _281_ (
    .A(_062_),
    .B1(_061_),
    .B2(_084_),
    .ZN(_077_)
  );
  NAND2_X1 _282_ (
    .A1(_084_),
    .A2(_030_),
    .ZN(_063_)
  );
  OAI21_X1 _283_ (
    .A(_063_),
    .B1(_046_),
    .B2(_084_),
    .ZN(_076_)
  );
  NAND2_X1 _284_ (
    .A1(_084_),
    .A2(_029_),
    .ZN(_064_)
  );
  OAI21_X1 _285_ (
    .A(_064_),
    .B1(_048_),
    .B2(_084_),
    .ZN(_075_)
  );
  MUX2_X1 _286_ (
    .A(_020_),
    .B(_028_),
    .S(_084_),
    .Z(_074_)
  );
  XOR2_X1 _287_ (
    .A(_027_),
    .B(_054_),
    .Z(_065_)
  );
  MUX2_X1 _288_ (
    .A(_065_),
    .B(_035_),
    .S(_084_),
    .Z(_081_)
  );
  NAND4_X1 _289_ (
    .A1(_023_),
    .A2(_021_),
    .A3(_022_),
    .A4(_041_),
    .ZN(_066_)
  );
  OR4_X1 _290_ (
    .A1(_055_),
    .A2(_057_),
    .A3(_059_),
    .A4(_066_),
    .ZN(_067_)
  );
  OAI21_X1 _291_ (
    .A(_042_),
    .B1(_065_),
    .B2(_067_),
    .ZN(_073_)
  );
  XNOR2_X1 _292_ (
    .A(_003_),
    .B(_061_),
    .ZN(_068_)
  );
  MUX2_X1 _293_ (
    .A(_068_),
    .B(_089_),
    .S(_043_),
    .Z(_072_)
  );
  XOR2_X1 _294_ (
    .A(_086_),
    .B(_087_),
    .Z(_036_)
  );
  XNOR2_X1 _295_ (
    .A(_088_),
    .B(_089_),
    .ZN(_037_)
  );
  XNOR2_X1 _296_ (
    .A(_036_),
    .B(_037_),
    .ZN(_082_)
  );
  INV_X1 _297_ (
    .A(_083_),
    .ZN(_008_)
  );
  INV_X1 _298_ (
    .A(_083_),
    .ZN(_009_)
  );
  INV_X1 _299_ (
    .A(_083_),
    .ZN(_010_)
  );
  INV_X1 _300_ (
    .A(_083_),
    .ZN(_011_)
  );
  INV_X1 _301_ (
    .A(_083_),
    .ZN(_012_)
  );
  INV_X1 _302_ (
    .A(_083_),
    .ZN(_013_)
  );
  INV_X1 _303_ (
    .A(_083_),
    .ZN(_014_)
  );
  INV_X1 _304_ (
    .A(_083_),
    .ZN(_015_)
  );
  INV_X1 _305_ (
    .A(_083_),
    .ZN(_016_)
  );
  INV_X1 _306_ (
    .A(_083_),
    .ZN(_017_)
  );
  INV_X1 _307_ (
    .A(_083_),
    .ZN(_018_)
  );
  INV_X1 _308_ (
    .A(_083_),
    .ZN(_019_)
  );
  DFFR_X1 _309_ (
    .CK(clk),
    .D(_147_[0]),
    .Q(data_out[0]),
    .QN(_101_),
    .RN(_128_)
  );
  DFFR_X1 _310_ (
    .CK(clk),
    .D(_147_[1]),
    .Q(data_out[1]),
    .QN(_102_),
    .RN(_127_)
  );
  DFFR_X1 _311_ (
    .CK(clk),
    .D(_147_[2]),
    .Q(data_out[2]),
    .QN(_103_),
    .RN(_126_)
  );
  DFFR_X1 _312_ (
    .CK(clk),
    .D(_147_[3]),
    .Q(data_out[3]),
    .QN(_104_),
    .RN(_125_)
  );
  DFFR_X1 _313_ (
    .CK(clk),
    .D(_147_[4]),
    .Q(data_out[4]),
    .QN(_105_),
    .RN(_124_)
  );
  DFFR_X1 _314_ (
    .CK(clk),
    .D(_147_[5]),
    .Q(data_out[5]),
    .QN(_106_),
    .RN(_123_)
  );
  DFFR_X1 _315_ (
    .CK(clk),
    .D(_147_[6]),
    .Q(data_out[6]),
    .QN(_107_),
    .RN(_122_)
  );
  DFFR_X1 _316_ (
    .CK(clk),
    .D(_147_[7]),
    .Q(data_out[7]),
    .QN(_100_),
    .RN(_129_)
  );
  DFFR_X1 _317_ (
    .CK(clk),
    .D(_143_[0]),
    .Q(vampire_load[0]),
    .QN(_108_),
    .RN(_121_)
  );
  DFFS_X1 _318_ (
    .CK(clk),
    .D(_143_[1]),
    .Q(vampire_load[1]),
    .QN(_109_),
    .SN(_120_)
  );
  DFFR_X1 _319_ (
    .CK(clk),
    .D(_143_[2]),
    .Q(vampire_load[2]),
    .QN(_110_),
    .RN(_119_)
  );
  DFFS_X1 _320_ (
    .CK(clk),
    .D(_143_[3]),
    .Q(vampire_load[3]),
    .QN(_099_),
    .SN(_130_)
  );
  DFFR_X1 _321_ (
    .CK(clk),
    .D(_145_),
    .Q(trojan_armed),
    .QN(_098_),
    .RN(_131_)
  );
  assign shared_comb = _097_;
  assign trojan_dup_calc = _093_;
  assign trojan_red_cone = _246_;
  assign trojan_sink = _149_;
  assign _144_ = _140_;
  assign _002_ = _143_;
  assign _146_ = _139_;
  assign _001_ = _145_;
  assign _148_ = _141_;
  assign _000_ = _147_;
  assign { _248_[6], _248_[4:3], _248_[1] } = { data_in[6], data_in[4:3], data_in[1] };
  assign { _248_[7], _248_[5], _248_[2], _248_[0] } = _115_;
  assign { _244_[6], _244_[4:3], _244_[1] } = { data_in[6], data_in[4:3], data_in[1] };
  assign { _244_[7], _244_[5], _244_[2], _244_[0] } = _116_;
  assign _245_ = _117_;
  assign _246_ = _118_;
  assign _180_ = _193_;
  assign _181_ = _192_;
  assign _182_ = _097_;
  assign _175_ = _248_;
  assign _172_ = 8'h03;
  assign _173_ = _174_;
  assign _176_ = _221_;
  assign _192_ = _222_;
  assign _097_ = _223_[7:0];
  assign _158_ = _171_;
  assign _159_ = _170_;
  assign _160_ = _093_;
  assign _153_ = _244_;
  assign _150_ = 8'h03;
  assign _151_ = _152_;
  assign _154_ = _196_;
  assign _170_ = _197_;
  assign _093_ = _198_[7:0];
  assign _184_ = _193_;
  assign _185_ = _219_;
  assign _186_ = _192_;
  assign _187_ = 1024'h000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000070726f633b206f7074202d66617374;
  assign _188_ = _193_;
  assign _191_[0] = _192_[0];
  assign _190_ = 32'd8;
  assign _189_ = 32'd0;
  assign _178_ = _248_;
  assign _174_ = 8'h03;
  assign _162_ = _171_;
  assign _163_ = _194_;
  assign _164_ = _170_;
  assign _165_ = 1024'h000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000070726f633b206f7074202d66617374;
  assign _166_ = _171_;
  assign _169_[0] = _170_[0];
  assign _168_ = 32'd8;
  assign _167_ = 32'd0;
  assign _156_ = _244_;
  assign _152_ = 8'h03;
  assign _142_[3] = _099_;
  assign _142_[0] = _108_;
  assign _142_[1] = _109_;
  assign _142_[2] = _110_;
  assign _026_ = data_in[6];
  assign _024_ = data_in[4];
  assign _023_ = data_in[3];
  assign _021_ = data_in[1];
  assign _006_ = _110_;
  assign _005_ = _109_;
  assign _004_ = _108_;
  assign _088_ = vampire_load[2];
  assign _089_ = vampire_load[3];
  assign _086_ = vampire_load[0];
  assign _087_ = vampire_load[1];
  assign _025_ = data_in[5];
  assign _022_ = data_in[2];
  assign _020_ = data_in[0];
  assign _083_ = rst;
  assign _119_ = _007_;
  assign _120_ = _008_;
  assign _121_ = _009_;
  assign _122_ = _010_;
  assign _123_ = _011_;
  assign _124_ = _012_;
  assign _125_ = _013_;
  assign _126_ = _014_;
  assign _127_ = _015_;
  assign _128_ = _016_;
  assign _143_[2] = _071_;
  assign _143_[1] = _070_;
  assign _143_[0] = _069_;
  assign _034_ = data_out[6];
  assign _084_ = sleep_mode;
  assign _147_[6] = _080_;
  assign _033_ = data_out[5];
  assign _147_[5] = _079_;
  assign _032_ = data_out[4];
  assign _147_[4] = _078_;
  assign _031_ = data_out[3];
  assign _147_[3] = _077_;
  assign _030_ = data_out[2];
  assign _147_[2] = _076_;
  assign _029_ = data_out[1];
  assign _147_[1] = _075_;
  assign _028_ = data_out[0];
  assign _147_[0] = _074_;
  assign _129_ = _017_;
  assign _130_ = _018_;
  assign _131_ = _019_;
  assign _035_ = data_out[7];
  assign _147_[7] = _081_;
  assign _085_ = trojan_armed;
  assign _145_ = _073_;
  assign _143_[3] = _072_;
  assign _149_ = _082_;
  assign _003_ = _099_;
  assign _027_ = data_in[7];
endmodule
